### ISSUE TITLE
Tres cool !

### ISSUE THREAD

**Issue by TheChatou** [tviejo/42Cursus-cub3d#28]
Salut Thomas ! Super projet, bravo ! Les mouvements de aut/bas en marchant sont super, c'est fluide et avec des mechaniques bien propres !
Je me permet d'inspecter ta mechanique de "crouch" !
Juste un petit truc, c'est dommage que le map Generator ne creer pas un fichier .cub avec les chemin des textures correspondantes, et la premiere map generee (1 40 30 20 5 3) J'etais bloque dans une piece, peut etre un soucis avec le floodfill.

**Comment by tviejo** [comment]
Merci beaucoup pour le retour ! Bonne idée pour le générateur de map, je viens de faire la generation de fichier .cub (modifiable à l'aide de defines dans le header). Je n'ai pas encore de flood fill, je vérifie de manière assez sommaire si le placement du joueur est possible, donc les erreurs sont normales (mais rares).
